#theme: jekyll-theme-architect
theme: minima

# Name of website
title: PowerWire
description: Independent IBM Power News

# Name to show in the footer
author: FormaServe

######################################
# --- Colours / background image --- #
######################################

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"